# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: tweetstream # MAKE SURE THIS MATCHES
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tweetstream
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username:
  password:
